### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by rockywind** [PJLab-ADG/neuralsim#1]

**Comment by ventusff** [comment]
Just in a few days :) I'm seperating away codes belonging to other future projects from the current codebase.

**Comment by rockywind** [comment]
Thanks a lot!

**Comment by wenbo-xu-official** [comment]
We are looking forward to your great work!

**Comment by andrearama** [comment]
Any idea when you will release it? Looking forward to it :)

**Comment by ventusff** [comment]
Hi @rockywind @waveleaf27 @wenbo-xu-official @andrearama , much much sorry for the late reply, the code has been released now :)

**Comment by ventusff** [comment]
Closing now as the code has been released.
