### ISSUE TITLE
About extract mono clues

### ISSUE THREAD

**Issue by toro1818** [PJLab-ADG/neuralsim#10]
I really appreciate your execellent work! But I have some questions about extract mono clues.
![image](https://github.com/PJLab-ADG/neuralsim/assets/63446843/75581b18-e2da-4bd0-93a5-1b44c90c0a96)
I'm confuzed about these three import.
when I run the extract_mono_cues.py, it'll failed when create  **DPTDepthModel**.
The error output is
**Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)+**

**Comment by toro1818** [comment]
sry， I‘ve handled it. I run the extract_mono_cues.py in nr3d env before.
When I move into omnidata env, it can run successifuly.

**Comment by ventusff** [comment]
Ah-ha. You may also consider installing the requirements for Omnidata and building Omnidata within the nr3d environment. In my previous attempts, I've never encountered conflicts between the dependencies and build of Omnidata with the nr3d environment :smile:. This might save you some trouble.
