### ISSUE TITLE
COLMAPDataset效果？

### ISSUE THREAD

**Issue by strualo** [PJLab-ADG/neuralsim#16]
请问COLMAPDataset是还在测试中吗？
目前COLMAPDataset的道路大范围场景效果有相关sample可以展示吗？
谢谢~

**Comment by ventusff** [comment]
你好，
目前 COLMAP dataset 主要是针对单物体和室内的数据集重建，（这部分效果已在 neus in 10 minutes 中有初步展示和可用配置）主要是我们手头没有 colmap 格式的街景数据 :( 

你如果有知道开源可用的 colmap 格式的街景数据或者愿意帮助处理提供的话，欢迎哈
