### ISSUE TITLE
How do you handle dynamic objects in training?

### ISSUE THREAD

**Issue by LMerCy** [PJLab-ADG/neuralsim#2]
It seems you are trying to evaluate your model in scenes with little dynamic objects,  but how do you handle dynamic object in training?

**Comment by ventusff** [comment]
In this paper, we manually select sequences with almost no dynamic objects. Even so, there will still be some dynamic pedestrians left (for example in seg153495 there are two pedestrians standing on the right side of the street), and in this case we use the "people" mask inferred using SegFormer to further ignore them in pixel sampling and pixel loss, following BlockNeRF's solution.

But this is a rare case, most of the selected (and trimmed as mentioned in supp) sequences contain literally no significant dynamc objects.

This is just a consideration of addressing issues one by one. We will deal with multiple-object reconstruction in a very soon upcoming work.

**Comment by LMerCy** [comment]
Great, looking foward to your future work!
