### ISSUE TITLE
Lidar Simulation

### ISSUE THREAD

**Issue by Madeline-hyh** [PJLab-ADG/neuralsim#28]
I really appreciate your execellent work! I am very interested in it, but now I have some issues when I try to use it for lidar simulation.
When I run the "python ./tools/render.py --resume_dir logs/streetsurf/seg100613 --no_cam --render_lidar lidar_model=original_reren --lidar_id=lidar_TOP --lidar_forward_inv_s=64000.0", I got the error "Aborted (core dumped)". And I use the gdb to debug,  it tells me "../sysdeps/unix/sysv/linux/raise.c: No such file or directory".

I do not know how to solve it, could please help me with it? Thanks.

**Comment by K0uya** [comment]
@ventusff 
could you give me some environmental tips in detail?
Thank you!
