### ISSUE TITLE
Support for PyTorch 2.0

### ISSUE THREAD

**Issue by lxxue** [PJLab-ADG/neuralsim#5]
Hi Jianfei,

Thanks for sharing the great work. I have a workstation with a 4090 which requires at least cuda 11.8. For cuda 11.8, pytorch only has wheels with versions >= 2.0. I saw you were doing some fixes for pytorch 2.0. I wonder if it is ready so I can start playing with the neuralsim repo?

**Comment by lxxue** [comment]
Update: I cloned the newest `nr3d_lib` with commit [b4c5d81](https://github.com/PJLab-ADG/nr3d_lib/commit/b4c5d81728c105959c02042001bc84eb142992d8). I experimented with scan 1 in Replica and results look good.

Sorry I just noticed the issue #4 so this one can be closed.

**Comment by ventusff** [comment]
:) Glad it works.
