### ISSUE TITLE
Variable name mistake.

### ISSUE THREAD

**Issue by filick** [PJLab-ADG/neuralsim#7]
Hi,

I think the `cam_front_tracks_in_world` in Line 311 should be `cam_front_poses_in_world`. Please take a look.

https://github.com/PJLab-ADG/neuralsim/blob/1341f50ac715a65504d9a71137ce203e480c1f34/dataio/autonomous_driving/custom/custom_autodrive_dataset.py#L306-L313

**Comment by ventusff** [comment]
Yes you are right. Thanks for pointing it out !
