### ISSUE TITLE
Posed monocular rgb as input

### ISSUE THREAD

**Issue by awarebayes** [PJLab-ADG/neuralsim#8]
Hello, thanks for your awesome work.
I want to apply it to posed monocular indoor scenes (some pretty large) (retail stores, my own dataset).
I have images and camera poses extracted with colmap (cvg/hloc)
What is the easiest way to do it? 
Which architecture should I try first?

**Comment by ventusff** [comment]
Hi,
I have just updated something you might need.

You could use `dataio.colmap_dataset.COLMAPDataset` in this case, with docs written [here](https://github.com/PJLab-ADG/neuralsim/tree/main/dataio/colmap).

As a starting point, I suggest you follow the monocular priors extraction process in the above link.

Then you can try with this experimental config [yaml](https://github.com/PJLab-ADG/neuralsim/blob/main/code_single/configs/exps/lotd_neus.colmap_indoor.230829.yaml).

You should carefully estimate the center and scale (`bounding_size`) of each of your dataset. I have provided some automatic tools in `nr3d_lib.geometry.normalize_views`, but they are mostly meant for object-centric datasets and not for indoor datasets.
